[package]
name = "parsimonious"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.1"
thiserror = "2.0.12"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "parse"
harness = false
